# Generated by Django 5.2.1 on 2025-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newssource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
