# Generated by Django 5.2.1 on 2025-06-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newssource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
