# Generated by Django 5.2.1 on 2025-07-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('news', '0005_alter_newsarticle_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='related_currencies',
            field=models.ManyToManyField(related_name='news_articles', to='core.currency'),
        ),
    ]
