# Generated by Django 5.2.1 on 2025-08-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
